<RelativeLayoutWidget>:
    RelativeLayout:
        Button:
            text:'C'
            size_hint:.3,.2
            pos_hint:{'right':1, 'top':1}

        Button:
            text:'Java'
            size_hint:.3,.2
            pos_hint:{'x':0, 'y':0}

        Button:
            text:'Python'
            size_hint:.3,.2
            pos_hint:{'center_x':.5, 'center_y':.5}

        Button:
            text:'Javascript'
            size_hint:.3,.2
            pos_hint:{'x':0, 'top':1}